# This is a basic workflow to help you get started with Actions

name: SimpleAction

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Environment variables at the global scope
env:
  nickname: ${{ github.actor }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "say_hello"
  say_hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      first_name: Jane

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to say_hello,
        echo test, and deploy your project.
    
    # Setup an environment variable you want available in the next step
    - name: Setup an environment variable
      run: |
        echo Currently the variable called \'nickname\' is set to \'${{ env.nickname }}\'
        echo "nickname=JD" >> $GITHUB_ENV
        echo Unfortunately, the variable called \'nickname\' is still set to \'${{ env.nickname }}\' within this context
    
    # Runs a pre-defined shell script, passing some environment variables as arguments
    - name: Run a shell script
      env:
        first_name: John
        last_name: Doe
      run: ./hello-world.sh ${{ env.first_name }} ${{ env.last_name }} ${{ env.nickname }}
      
